### PR TITLE
Adding more controllers

### PR DESCRIPTION
**Pull request by jlbeard84**
- Extracted some common db logic
- Added db methods to get new entity (Developer)
- Added new controller
- Cleaned up some other entities

### CODE REVIEW

**Comment by jlbeard84** [comment]
- Added methods for Series

**Comment by jlbeard84** [comment]
Added methods for Mechanic

**Comment by jlbeard84** [comment]
- Added methods for OST
- Added methods for Platform

**Comment by jlbeard84** [comment]
- Added methods for Staff
- Added methods for Release

**Review by bferguson3 — COMMENTED** [review]
I would not have known to take this direction

**Pull request merged**
